### ISSUE TITLE
[1.18.2] Broken interaction with Repurposed Structures and More Villagers mods

### ISSUE THREAD

**Issue by StanTheMachinegun** [vectorwing/FarmersDelight#487]
After some troubleshooting, it looks like leaving the parameter genVillageCompostHeaps = true in the config fumbles with the built-in limits of structures for Repurposed Structures Villages. Usually, all the "work site" structures in RS are capped at 1, but somehow Farmer's Delight removes that cap, but only for non-FD structures. The result is, that you on average end up with 3 foresters 2 florists and 4 oceanographer houses on average village, leaving no room for vanilla work stations.

Here's a thread where I discussed the issue fith RS author and where we did most of the troubleshooting:
https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-more-villagers-datapack#c10

**Comment by vectorwing** [comment]
I know this issue is fairly old by now, but I tried taking a look at it recently to see what was up.

After making an instance with More Villagers, RS, FD and the RS+MV datapack, I made a few worlds with and without FD's compost houses enabled to see if it had any impact on MV job rates.

Generally, it felt inconclusive: even with FD uninstalled or the config disabled, many villages, either vanilla or RS, would display many MV jobs more than once, sometimes in excess, but also generating vanilla houses now and then. In some cases, when re-enabling FD's config, the village would generate with more MV or less MV similarly.

Either way, this kind of thing is normal for villages. Even on the same seed, a village will "scramble" completely when elements are added, rolling an entirely different set of structures than before. This can coincidentally seem like it's causing problems, but I couldn't replicate it on my end; More Villagers does not seem to have any upper limits to how many of its structures can generate.

For RS villages in particular, FD does not touch them; it only ever adds structures to vanilla village pools. So if the issue resides there, it theoretically should not have an effect.

@StanTheMachinegun, is this issue still happening? Or did updating the mods fix it from back then?

**Comment by StanTheMachinegun** [comment]
Hello,
Since I moved on to 1.19.2 this year, the issue seems to be gone, I'm running a mod-heavy modpack, and I did notice, that More Villagers is a little bit more strict in enforcing 1 specific job site per village.

**Comment by vectorwing** [comment]
Ah, good to hear! 😄
I'll be closing this issue as unrelated, then. If the conflict does return, feel free to reopen this. 👍

**Comment by TelepathicGrunt** [comment]
Just fyi, for Repurposed Structures, it's actually my mod that does the limiting. I added a system to the compat datapacks that lets me specify the max number of times a house can show up in one village. So in all my compat datapacks, I make sure each modded house cannot show up more than once per village to allow more modded houses to show up and not overcrowd the villages

Can't remember what was discussed back then but could've been my 1.18.2 system wasn't working properly and was fixed in 1.19.2

**Comment by StanTheMachinegun** [comment]
Hello Gentlemen,

It seems that the issue persist again, with spawning villages almost exclusively with houses from RS compat packs (currently More Villagers and Farmer's Delight), but it doesn't appear in plains villages. I'll try to do some troubleshooting and see, which mod of the three (or compat datapacks) causes the issue.

**Comment by TelepathicGrunt** [comment]
@StanTheMachinegun what Mc version? Also, it would be an issue on repurposed structures side. Not farmer’s delight
